using System;
using System.Collections.ObjectModel;
using System.Windows;
using System.Windows.Controls;

namespace Timelapse.Controls
{
    /// <summary>
    /// This user control contains a grid with four columns, labeled File Name, Status, Original date/time, New date/time, and Difference
    /// It is used to display feedback about any date changes that  may be made or that have been made
    /// The primary way to invoke this is to add the control to the UI, and then invoke
    /// AddFeedbackRow (...), which will add a row to the grid whose contents reflect the contents of the various parameters.
    /// </summary>
    public partial class DateChangesFeedbackControl : UserControl
    {
        // Whether to show the difference column
        public bool ShowDifferenceColumn { get; set; }
        public string Column0Name { get; set; }
        public string Column1Name { get; set; }
        public string Column2Name { get; set; }
        public string Column3Name { get; set; }
        public string Column4Name { get; set; }
        // This collection will hold tuples, where each tuple contains the contents for a row that will be shown in the datagrid  
        private readonly ObservableCollection<FeedbackRowTuple> feedbackRows;

        // Initialization: Bind the collection to the datagrid, where any change in the collection will be displayed in the datagrid
        public DateChangesFeedbackControl()
        {
            this.InitializeComponent();
            this.Column0Name = "File";
            this.Column1Name = "Status";
            this.Column2Name = "Current date/time";
            this.Column3Name = "New date/time";
            this.Column4Name = "Difference";
            this.feedbackRows = new ObservableCollection<FeedbackRowTuple>();
            this.feedbackGrid.ItemsSource = this.feedbackRows;
        }

        // Add a row to the tuple, which in turn will update the grid. 
        // Also ensures the latest added row is in view.
        public void AddFeedbackRow(string fileName, string status, string oldDateTime, string newDateTime, string difference)
        {
            FeedbackRowTuple row = new FeedbackRowTuple(fileName, status, oldDateTime, newDateTime, difference);
            this.feedbackRows.Add((FeedbackRowTuple)row);
            this.feedbackGrid.ScrollIntoView(this.feedbackGrid.Items[this.feedbackGrid.Items.Count - 1]);
        }

        // Label the datagrid feedback columns with the appropriate headers
        private void DatagridFeedback_AutoGeneratedColumns(object sender, EventArgs e)
        {
            this.feedbackGrid.Columns[0].Header = this.Column0Name;
            this.feedbackGrid.Columns[1].Header = this.Column1Name;
            this.feedbackGrid.Columns[2].Header = this.Column2Name;
            this.feedbackGrid.Columns[3].Header = this.Column3Name;
            this.feedbackGrid.Columns[4].Header = this.Column4Name;
            if (this.ShowDifferenceColumn == false)
            {
                this.feedbackGrid.Columns[4].Visibility = Visibility.Collapsed;
            }
        }

        // This class defines a row tuple containing 5 elements, which is used as a row in the datagrid.
        private class FeedbackRowTuple
        {
            public string FileName { get; set; }
            public string Status { get; set; }
            public string OldDateTime { get; set; }
            public string NewDateTime { get; set; }
            public string Difference { get; set; }

            public FeedbackRowTuple(string fileName, string status, string oldDateTime, string newDateTime, string difference)
            {
                this.FileName = fileName;
                this.Status = status;
                this.OldDateTime = oldDateTime;
                this.NewDateTime = newDateTime;
                this.Difference = difference;
            }
        }
    }
}
